## **PANDAS**

* Introduction to Pandas library which is one of the important library for data analytics. We'll cover what is a dataframe and series.
* Data Manipulation with Pandas.
* We will explore various functions available in the Pandas library.

## **Introduction to Pandas**<a name="pandas"></a>

* Pandas is a Python library which is primarily used for tabular data manipulation and analysis.
* Specifically, it provides us with data structures called as Series and DataFrames.
* The name Pandas is derived from the word Panel Data – an Econometrics from Multidimensional data.
* Pandas internally uses NumPy for storing the data efficiently.

In [3]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
type(pd)

module

In [3]:
# Check Pandas version

print(pd.__version__)

2.2.3

## **Dataframe and Series** <a name="data-frame-series"></a>

* A series is essentially a column and dataframe is a multi-dimensional table made up of collection of series.

In [4]:
# Creating pandas series
cars =  ['Comet', 'Tiago', 'i20']

series = pd.Series(data=cars)

print(series)
print(f"Type of series: {type(series)}")

0    Comet
1    Tiago
2      i20
dtype: object
Type of series: <class 'pandas.core.series.Series'>

In [4]:
#Creating pandas dataframe
df = pd.DataFrame({'cars': ['Comet', 'Tiago', 'i20'],
                    'Brands': ['MG', 'Tata', 'Hyundai'],
                    'Age': [2, 7, 9]})

print(df)
print(f"Type of df: {type(df)}")

    cars   Brands  Age
0  Comet       MG    2
1  Tiago     Tata    7
2    i20  Hyundai    9
Type of df: <class 'pandas.core.frame.DataFrame'>

## **How to read files of different format** <a name="read-csv-files"></a>

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')
import os
from pathlib import Path
base_dir = Path.cwd()
file_path = os.path.join(base_dir, "DATA", "Iris_data_sample.csv")
file_path_xls = os.path.join(base_dir, "DATA", "Iris_data_sample.xlsx")
file_path_txt = os.path.join(base_dir, "DATA", "Iris_data_sample.txt")
file_path_toyota = os.path.join(base_dir, "DATA", "Toyota.csv")
print(file_path)
# sep='/t' is used as the csv file is seperated with a tab spacing

#### **Reading .csv format data**

In [6]:
data_csv = pd.read_csv(file_path)
data_csv.head(10)

,Unnamed: 0,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,NaN,1.4,0.2,NaN
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,??,3.1,1.5,0.2,Iris-setosa
4,5,5,3.6,###,0.2,Iris-setosa
5,6,5.4,3.9,NaN,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa

In [7]:
# =============================================================================
# Setting the 1st coulmn 'Unnamed: 0' as index column while reading data
# =============================================================================
data_csv = pd.read_csv(file_path,index_col=0)
data_csv.head()

  SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm      Species
1           5.1           3.5           1.4           0.2  Iris-setosa
2           4.9           NaN           1.4           0.2          NaN
3           4.7           3.2           1.3           0.2  Iris-setosa
4            ??           3.1           1.5           0.2  Iris-setosa
5             5           3.6           ###           0.2  Iris-setosa

In [8]:
# =============================================================================
# Replacing ‘??’ and ‘# # #’ as 'nan' values
# =============================================================================
data_csv = pd.read_csv(file_path,index_col=0,na_values=["??"])
data_csv = pd.read_csv(file_path,index_col=0,na_values=["??","###"])
data_csv.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa

#### **Reading .xlsx format data**

In [44]:
data_xlsx = pd.read_excel(file_path_xls,
                        sheet_name='Iris_data')

data_xlsx = pd.read_excel(file_path_xls,index_col=0)

data_xlsx = pd.read_excel(file_path_xls,
                        index_col=0,
                        na_values=["??","###"])

In [27]:
data_xlsx.head(6)

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa
6            5.4           3.9            NaN           0.4  Iris-setosa

#### **Reading .txt format data**


 - Delimitor can be a space or a tab               
 - Try out to see what works

In [45]:

#Instead of using read_table(), read_csv() can also be used to read .txt files
data_txt1 = pd.read_csv(file_path_txt,delimiter=" ")
data_txt1.head()

,Unnamed: 0,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,1,5.1,3.5,1.4,0.2,Iris-setosa
2,2,4.9,3.0,1.4,0.2,Iris-setosa
3,3,4.7,3.2,1.3,0.2,Iris-setosa
4,4,4.6,3.1,1.5,0.2,Iris-setosa
5,5,5.0,3.6,1.4,0.2,Iris-setosa

# Toyota cars - case study

In [10]:
# =============================================================================
# Importing data
# =============================================================================
# By passing 'index_col=0', first column becomes the index column
cars_data = pd.read_csv(file_path_toyota, index_col=0)

In [11]:
# =============================================================================
# Creating copy of original data
# =============================================================================
'''
In Python, there are two ways to create copies
 * Shallow copy :
 - It only creates a new variable that shares the reference of the original object
 - Any changes made to a copy of object will be reflected in the original object as well
 * Deep copy:
 - In case of deep copy, a copy of object is copied in other object with no
   reference to the original
 - Any changes made to a copy of object will not be reflected in the original object
'''
# shallow copy
samp = cars_data
samp = cars_data.copy(deep=False)

# deep copy
cars_data1 = cars_data.copy()
cars_data1 = cars_data.copy(deep=True)

In [12]:

# =============================================================================
# Attributes of data
# =============================================================================
print(cars_data1.index)         # to get the index (row labels) of the dataframe
print(cars_data1.columns)       # to get the column labels of the dataframe
print(cars_data1.size)          # to get the total number of elements from the dataframe
print(cars_data1.shape)         # to get the dimensionality of the dataframe
print(cars_data1.memory_usage())# to get the memory usage of each column in bytes
print(cars_data1.ndim)          # to get the number of axes / array dimensions
                         # a two-dimensional array stores data in a format
                         # consisting of rows and columns

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435],
      dtype='int64', length=1436)
Index(['Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor', 'Automatic', 'CC',
       'Doors', 'Weight'],
      dtype='object')
14360
(1436, 10)
Index        11488
Price        11488
Age          11488
KM           11488
FuelType     11488
HP           11488
MetColor     11488
Automatic    11488
CC           11488
Doors        11488
Weight       11488
dtype: int64
2

In [33]:
cars_data1.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435],
      dtype='int64', length=1436)

In [ ]:
cars_data1.columns

In [ ]:
cars_data1.size

In [ ]:
cars_data1.shape

In [49]:
cars_data1.memory_usage()

Index        11488
Price        11488
Age          11488
KM           11488
FuelType     11488
HP           11488
MetColor     11488
Automatic    11488
CC           11488
Doors        11488
Weight       11488
dtype: int64

In [50]:
cars_data1.ndim

2

In [51]:
# =============================================================================
# Indexing and selecting data
# =============================================================================
"""
 - Python slicing operator ‘[ ]’ and attribute/ dot operator ‘. ’  are used
   for indexing
 - Provides quick and easy access to pandas data structures
"""
cars_data1.head(6) # The function head returns the first n rows from the dataframe
                   # By default, the head() returns first 5 rows

   Price   Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500  23.0  46986   Diesel  90       1.0          0  2000  three    1165
1  13750  23.0  72937   Diesel  90       1.0          0  2000      3    1165
2  13950  24.0  41711   Diesel  90       NaN          0  2000      3    1165
3  14950  26.0  48000   Diesel  90       0.0          0  2000      3    1165
4  13750  30.0  38500   Diesel  90       0.0          0  2000      3    1170
5  12950  32.0  61000   Diesel  90       0.0          0  2000      3    1170

In [52]:
cars_data1.tail(5) # The function tail returns the last n rows
                   # for the object based on position

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
1431,7500,NaN,20544,Petrol,86,1.0,0,1300,3,1025
1432,10845,72.0,??,Petrol,86,0.0,0,1300,3,1015
1433,8500,NaN,17016,Petrol,86,0.0,0,1300,3,1015
1434,7250,70.0,??,NaN,86,1.0,0,1300,3,1015
1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

In [53]:
"""
 -  To access a scalar value, the fastest way is to use the 'at' and 'iat' methods
 - 'at' provides label-based scalar lookups
 - 'iat' provides integer-based lookups
"""
cars_data1.at[4,'FuelType'] # value corresponds to 5th row & 'FuelType' column

'Diesel'

In [58]:
print(cars_data1.iat[5,6])         # value corresponds to 6th row & 7th column
print(cars_data1.at[5,'Automatic'])

0
0

In [59]:

"""
    To access a group of rows and columns by label(s) .loc[ ] can be used
"""
cars_data1.loc[:,'FuelType']

0       Diesel
1       Diesel
2       Diesel
3       Diesel
4       Diesel
         ...
1431    Petrol
1432    Petrol
1433    Petrol
1434       NaN
1435    Petrol
Name: FuelType, Length: 1436, dtype: object

# Data types

    - The way information gets stored in a dataframe or a python object affects
      the analysis and outputs of calculations
    - There are two main types of data : numeric and character types
    - Numeric data types includes integers and floats
    - For example: integer – 10, float – 10.53    
    - Strings are known as objects in pandas which can store values that contain
    - numbers and / or characters
    - For example: ‘category1’

In [13]:
# =============================================================================
# Checking data types of each column
# =============================================================================
cars_data1.dtypes             # returns a series with the data type of each column

Price          int64
Age          float64
KM            object
FuelType      object
HP            object
MetColor     float64
Automatic      int64
CC             int64
Doors         object
Weight         int64
dtype: object

In [61]:
# =============================================================================
# Count of Unique Data Types
# =============================================================================

cars_data1.dtypes.value_counts()

int64      4
object     4
float64    2
Name: count, dtype: int64

In [14]:
# =============================================================================
# Selecting data based on data types
# =============================================================================
cars_data1.select_dtypes(exclude=[object])
# returns a subset of the columns from dataframe by excluding columns of object data

      Price   Age  MetColor  Automatic    CC  Weight
0     13500  23.0       1.0          0  2000    1165
1     13750  23.0       1.0          0  2000    1165
2     13950  24.0       NaN          0  2000    1165
3     14950  26.0       0.0          0  2000    1165
4     13750  30.0       0.0          0  2000    1170
...     ...   ...       ...        ...   ...     ...
1431   7500   NaN       1.0          0  1300    1025
1432  10845  72.0       0.0          0  1300    1015
1433   8500   NaN       0.0          0  1300    1015
1434   7250  70.0       1.0          0  1300    1015
1435   6950  76.0       0.0          0  1600    1114

[1436 rows x 6 columns]

# Concise summary of dataframe

info():

returns a concise summary of a dataframe

    - data type of index
    - data type of columns
    - count of non-null values

In [15]:
cars_data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1436 non-null   object
 3   FuelType   1336 non-null   object
 4   HP         1436 non-null   object
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 123.4+ KB

# Checking format of each column

By using info(), we can see
    
    - ‘KM’ has been read as object instead of integer
    
    - ‘HP’ has been read as object instead of integer
    
    - ‘MetColor’ and ‘Automatic’ have been read as float64 and int64 respectively
    
       since it has values 0/1
    
    - Ideally, ‘Doors’ should’ve been read as int64 since it has values 2, 3, 4, 5.
    
      But it has been read as object
    
    - Missing values present in few variables

Let’s encounter the reason !

 Unique elements of columns:
 unique() is used to find the unique elements of a column """

In [16]:
print(np.unique(cars_data1['KM'])) # ‘KM’ has special character to it '??'
                                   # Hence, it has been read as object instead of int64

['1' '10000' '100123' ... '99865' '99971' '??']

In [17]:

print(np.unique(cars_data1['HP'])) # ‘HP’ has special character to it '????'
                                   # Hence, it has been read as object instead of int64

['107' '110' '116' '192' '69' '71' '72' '73' '86' '90' '97' '98' '????']

In [18]:


print(np.unique(cars_data1['MetColor'])) # ‘MetColor’ have been read as float64
                                         #  since it has values 0. & 1.

[ 0.  1. nan]

In [19]:
print(np.unique(cars_data1['Automatic']))# ‘Automatic’ has been read as int64
                                         #  since it has values 0 & 1

[0 1]

In [20]:

print(np.unique(cars_data1['Doors']))    # ‘Doors’ has been read as object
                                         # instead of int64 because of values
                                         # ‘five’ ‘four’ ‘three’ which are strings

['2' '3' '4' '5' 'five' 'four' 'three']


### Importing data (replacing special chars with nan values)

    - We need to know how missing values are represented in the dataset
      in order to make reasonable decisions
    - The missing values exist in the form of ‘nan’, '??', '????'
    - Python, by default replace blank values with ‘nan’
    - Now, importing the data considering other forms of missing values in a dataframe

In [27]:
cars_data = pd.read_csv(file_path_toyota, index_col=0, na_values=["??","????"])
cars_data.head()

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.0,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.0,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.0,38500.0,Diesel,90.0,0.0,0,2000,3,1170

In [26]:
cars_data.info() # Summary - after replacing special characters with nan

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   object
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 123.4+ KB
[1.0000e+00 1.5000e+01 2.2500e+02 ... 2.3294e+05 2.4300e+05        nan]

### Converting variable’s data types

In [28]:

""" astype() method is used to explicitly convert data types from one to another"""

# Converting ‘MetColor’ , ‘Automatic’ to object data type

cars_data['MetColor']  = cars_data['MetColor'].astype('object')
cars_data['Automatic'] = cars_data['Automatic'].astype('object')

In [29]:

# If ‘FuelType’ is of object data type,
cars_data['FuelType'].nbytes                     # 11488

11488

In [30]:
# =============================================================================
# category vs object data type
# =============================================================================
""" nbytes() is used to get the total bytes consumed by the elements of the columns"""

# If ‘FuelType’ is of category data type,
cars_data['FuelType'].astype('category').nbytes # 1460

1460

In [31]:

# Re-checking the data type of variables after all the conversions
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   object
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   object
 6   Automatic  1436 non-null   object
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(3), int64(3), object(4)
memory usage: 123.4+ KB

In [37]:
# =============================================================================
# Cleaning column ‘Doors’
# =============================================================================
# Checking unique values of variable ‘Doors’ :

#print(np.unique(cars_data['Doors']))

"""
    replace() is used to replace a value with the desired value
    Syntax: DataFrame.replace([to_replace, value, …])
"""

cars_data['Doors'].replace('three',3,inplace=True)
cars_data['Doors'].replace('four',4,inplace=True)
cars_data['Doors'].replace('five',5,inplace=True)

In [41]:
# To check the frequencies of unique cateogories in a variable
cars_data['Doors'].value_counts()

Doors
5    674
3    622
4    138
2      2
Name: count, dtype: int64

In [38]:

"""
   (or) Pandas- where()
"""
cars_data['Doors'].where(cars_data['Doors']!='three',3,inplace=True)

In [40]:
"""
   (or) Numpy- where()
"""
cars_data['Doors'] = np.where(cars_data['Doors']=='five',5,cars_data['Doors'])

# Converting ‘Doors’ to int64:
cars_data['Doors'] = cars_data['Doors'].astype('int64')
cars_data['Doors'].value_counts()
print(np.unique(cars_data['Doors']))

[2 3 4 5]

### Cross tables & Correlation

   pandas.crosstab()

    - To compute a simple cross-tabulation of one, two (or more) factors
    - By default computes a frequency table of the factors

In [42]:
cars_data2 = cars_data.copy()

**One-way table**

In [44]:
pd.crosstab(index=cars_data2['FuelType'], columns='count', dropna=True)

col_0     count
FuelType
CNG          15
Diesel      144
Petrol     1177

 Most of the cars have petrol as fuel type

**Two-way table**

To look at the frequency distribution of gearbox types with respect to different fuel types of the cars

In [99]:
pd.crosstab(index   = cars_data2['Automatic'],
            columns = cars_data2['FuelType'],
            dropna  = True)

FuelType   CNG  Diesel  Petrol
Automatic
0           15     144    1104
1            0       0      73

**Two-way table with proportion / Joint probability**

Joint probability is the likelihood of two independent events happening at the same time

In [100]:
pd.crosstab(index     = cars_data2['Automatic'],
            columns   = cars_data2['FuelType'],
            normalize = True,
            dropna    = True)

FuelType        CNG    Diesel    Petrol
Automatic
0          0.011228  0.107784  0.826347
1          0.000000  0.000000  0.054641

0.82 => Joint probability of manual gear box and petrol fuel type

**Two-way table - Marginal probability**

Marginal probability is the probability of the occurrence of the single event

In [101]:
pd.crosstab(index     = cars_data2['Automatic'],
            columns   = cars_data2['FuelType'],
            margins   = True,
            dropna    = True,
            normalize = True)

FuelType        CNG    Diesel    Petrol       All
Automatic
0          0.011228  0.107784  0.826347  0.945359
1          0.000000  0.000000  0.054641  0.054641
All        0.011228  0.107784  0.880988  1.000000

Probability of cars having manual gear box when the fuel type are
CNG or Diesel or Petrol is 0.95

**Two-way table - Conditional probability=> Row sum = 1**




Conditional probability is the probability of an event ( A ), given that
another event ( B ) has already occurred

In [102]:
pd.crosstab(index     = cars_data2['Automatic'],
            columns   = cars_data2['FuelType'],
            margins   = True,
            dropna    = True,
            normalize = 'index')

# Given the gear box, probability of different fuel type

FuelType        CNG    Diesel    Petrol
Automatic
0          0.011876  0.114014  0.874109
1          0.000000  0.000000  1.000000
All        0.011228  0.107784  0.880988

**Two-way table - Conditional probability => Column sum =1**

In [103]:
pd.crosstab(index     = cars_data2['Automatic'],
            columns   = cars_data2['FuelType'],
            margins   = True,
            dropna    = True,
            normalize = 'columns')

# Given the fuel type, probability of different gear box

FuelType   CNG  Diesel    Petrol       All
Automatic
0          1.0     1.0  0.937978  0.945359
1          0.0     0.0  0.062022  0.054641

   
### Correlation    
Correlation: the strength of association between two variables

In [104]:
# Excluding the categorical variables to find the correlation

numerical_data = cars_data2.select_dtypes(exclude=[object])
print(numerical_data.shape)

# Finding the correlation between numerical variables
corr_matrix = numerical_data.corr()
print(corr_matrix)

(1436, 7)
           Price       Age        KM        HP        CC     Doors    Weight
Price   1.000000 -0.878407 -0.574720  0.309902  0.165067  0.185326  0.581198
Age    -0.878407  1.000000  0.512735 -0.157904 -0.120706 -0.157027 -0.464299
KM     -0.574720  0.512735  1.000000 -0.335285  0.299993 -0.036191 -0.026271
HP      0.309902 -0.157904 -0.335285  1.000000  0.053758  0.097162  0.086737
CC      0.165067 -0.120706  0.299993  0.053758  1.000000  0.126768  0.651450
Doors   0.185326 -0.157027 -0.036191  0.097162  0.126768  1.000000  0.302618
Weight  0.581198 -0.464299 -0.026271  0.086737  0.651450  0.302618  1.000000

In [105]:

# Rounding off to two decimal places
print(round(corr_matrix,2))

        Price   Age    KM    HP    CC  Doors  Weight
Price    1.00 -0.88 -0.57  0.31  0.17   0.19    0.58
Age     -0.88  1.00  0.51 -0.16 -0.12  -0.16   -0.46
KM      -0.57  0.51  1.00 -0.34  0.30  -0.04   -0.03
HP       0.31 -0.16 -0.34  1.00  0.05   0.10    0.09
CC       0.17 -0.12  0.30  0.05  1.00   0.13    0.65
Doors    0.19 -0.16 -0.04  0.10  0.13   1.00    0.30
Weight   0.58 -0.46 -0.03  0.09  0.65   0.30    1.00

### Identifying missing values

 - In Pandas dataframes, missing data is represented by NaN
  (an acronym for Not a Number)
 - To check null values in Pandas dataframes, isnull() and isna() are used
 - These functions returns a dataframe of Boolean values which are True for NaN values

In [106]:
cars_data2 = cars_data.copy()
cars_data3 = cars_data2.copy()

In [107]:
# To check the count of missing values present in each column

print('Data columns with null values:\n')
cars_data2.isna().sum()   #or

Data columns with null values:

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [108]:
cars_data2.isnull().sum()

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [109]:
# Subsetting the rows that have one or more missing values
missing = cars_data2[cars_data2.isnull().any(axis=1)]
missing

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
6,16900,27.0,NaN,Diesel,NaN,NaN,0,2000,3,1245
7,18600,30.0,75889.0,NaN,90.0,1.0,0,2000,3,1245
9,12950,23.0,71138.0,Diesel,NaN,NaN,0,1900,3,1105
15,22000,28.0,18739.0,Petrol,NaN,0.0,0,1800,3,1185
...,...,...,...,...,...,...,...,...,...,...
1428,8450,72.0,NaN,Petrol,86.0,NaN,0,1300,3,1015
1431,7500,NaN,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.0,NaN,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,NaN,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.0,NaN,NaN,86.0,1.0,0,1300,3,1015


### Imputing missing values

Explore Distributions:

In [43]:
cars_data2.describe()

,Price,Age,KM,HP,CC,Doors,Weight
count,1436.000000,1336.000000,1421.000000,1430.000000,1436.000000,1436.000000,1436.00000
mean,10730.824513,55.672156,68647.239972,101.478322,1566.827994,4.033426,1072.45961
std,3626.964585,18.589804,37333.023589,14.768255,187.182436,0.952677,52.64112
min,4350.000000,1.000000,1.000000,69.000000,1300.000000,2.000000,1000.00000
25%,8450.000000,43.000000,43210.000000,90.000000,1400.000000,3.000000,1040.00000
50%,9900.000000,60.000000,63634.000000,110.000000,1600.000000,4.000000,1070.00000
75%,11950.000000,70.000000,87000.000000,110.000000,1600.000000,5.000000,1085.00000
max,32500.000000,80.000000,243000.000000,192.000000,2000.000000,5.000000,1615.00000

In [111]:
cars_data2.describe(include="O")

       FuelType  MetColor  Automatic
count      1336    1286.0       1436
unique        3       2.0          2
top      Petrol       1.0          0
freq       1177     868.0       1356

In [112]:
cars_data2.describe(include="all")

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
count,1436.000000,1336.000000,1421.000000,1336,1430.000000,1286.0,1436.0,1436.000000,1436.000000,1436.00000
unique,NaN,NaN,NaN,3,NaN,2.0,2.0,NaN,NaN,NaN
top,NaN,NaN,NaN,Petrol,NaN,1.0,0.0,NaN,NaN,NaN
freq,NaN,NaN,NaN,1177,NaN,868.0,1356.0,NaN,NaN,NaN
mean,10730.824513,55.672156,68647.239972,NaN,101.478322,NaN,NaN,1566.827994,4.033426,1072.45961
std,3626.964585,18.589804,37333.023589,NaN,14.768255,NaN,NaN,187.182436,0.952677,52.64112
min,4350.000000,1.000000,1.000000,NaN,69.000000,NaN,NaN,1300.000000,2.000000,1000.00000
25%,8450.000000,43.000000,43210.000000,NaN,90.000000,NaN,NaN,1400.000000,3.000000,1040.00000
50%,9900.000000,60.000000,63634.000000,NaN,110.000000,NaN,NaN,1600.000000,4.000000,1070.00000
75%,11950.000000,70.000000,87000.000000,NaN,110.000000,NaN,NaN,1600.000000,5.000000,1085.00000
max,32500.000000,80.000000,243000.000000,NaN,192.000000,NaN,NaN,2000.000000,5.000000,1615.00000

In [118]:
# Inspect distributions to guide method choice
desc = cars_data2.describe(include="number").T
skew = cars_data2.select_dtypes(include=["int64", "float64"]).skew(numeric_only=True).to_frame("skew")
desc.join(skew, how="left")

,count,mean,std,min,25%,50%,75%,max,skew
Price,1436.0,10730.824513,3626.964585,4350.0,8450.0,9900.0,11950.0,32500.0,1.703885
Age,1336.0,55.672156,18.589804,1.0,43.0,60.0,70.0,80.0,-0.801266
KM,1421.0,68647.239972,37333.023589,1.0,43210.0,63634.0,87000.0,243000.0,1.007788
HP,1430.0,101.478322,14.768255,69.0,90.0,110.0,110.0,192.0,0.858657
CC,1436.0,1566.827994,187.182436,1300.0,1400.0,1600.0,1600.0,2000.0,0.607241
Doors,1436.0,4.033426,0.952677,2.0,3.0,4.0,5.0,5.0,-0.076395
Weight,1436.0,1072.459610,52.641120,1000.0,1040.0,1070.0,1085.0,1615.0,3.108639

In [114]:
# Audit missingness
# Calculate the percentage of missing values for each column
missing_pct = (cars_data2.isnull().sum() / len(cars_data2)) * 100

# Create a DataFrame to display the missing counts and percentages
missing_report = pd.DataFrame({
    'missing_count': cars_data2.isnull().sum(),
    'missing_pct': missing_pct
})

# Display the report
display(missing_report)

           missing_count  missing_pct
Price                  0     0.000000
Age                  100     6.963788
KM                    15     1.044568
FuelType             100     6.963788
HP                     6     0.417827
MetColor             150    10.445682
Automatic              0     0.000000
CC                     0     0.000000
Doors                  0     0.000000
Weight                 0     0.000000

In [115]:
cars_data2['KM'].isnull().sum()

np.int64(15)

### Replacing 'Age' with mean

In [116]:
# Step 1: Calculate overall median (fallback)
overall_age_median = cars_data2['Age'].median()
overall_age_median

60.0

In [117]:
# Step 2: Create a mapping of FuelType → median Age
fueltype_age_medians = cars_data2.groupby('FuelType')['Age'].median()
fueltype_age_medians

FuelType
CNG       57.0
Diesel    56.0
Petrol    61.0
Name: Age, dtype: float64

In [ ]:
# Step 3: Fill missing Age by mapping FuelType-specific medians
cars_data2['Age'] = cars_data2['Age'].fillna(
    cars_data2['FuelType'].map(fueltype_age_medians)
)

# Step 4: Fill any remaining with overall median
cars_data2['Age'] = cars_data2['Age'].fillna(overall_age_median)

In [ ]:
# Step 1: Calculate overall median (fallback)
overall_age_median = cars_data2['Age'].median()

# Step 2: Create a mapping of FuelType → median Age
fueltype_age_medians = cars_data2.groupby('FuelType')['Age'].median()

# Step 3: Fill missing Age by mapping FuelType-specific medians
cars_data2['Age'] = cars_data2['Age'].fillna(
    cars_data2['FuelType'].map(fueltype_age_medians)
)

# Step 4: Fill any remaining with overall median
cars_data2['Age'] = cars_data2['Age'].fillna(overall_age_median)

In [ ]:
cars_data2['Age'].isnull().sum()

### Replacing 'KM' with median

In [ ]:
cars_data2['KM'].median()

In [ ]:
cars_data2['KM'].fillna(cars_data2['KM'].median(), inplace = True)

### Replacing 'HP' with mean

In [ ]:
cars_data2['HP'].mean()

cars_data2['HP'].fillna(cars_data2['HP'].mean(), inplace = True)

cars_data2['HP'].isnull().sum()

In [47]:
# Check for missing data after filling values
cars_data2.isnull().sum()

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

### Replacing 'Fuel Type' with mode

- Returns a Series containing counts of unique values
- The values will be in descending order so that the first element is
  the most frequently-occurring element
- Excludes NA values by default

In [ ]:
cars_data2['FuelType'].value_counts()

In [ ]:
# To get the mode value of FuelType
cars_data2['FuelType'].value_counts().index[0]

In [ ]:
# To fill NA/NaN values using the specified value
cars_data2['FuelType'].fillna(cars_data2['FuelType']\
      .value_counts().index[0],\
      inplace = True)

In [ ]:
cars_data2['FuelType'].isnull().sum()

###  Replacing 'MetColor' with mode

In [ ]:
# To get the mode value of Metcolor
cars_data2['MetColor'].mode()

In [45]:
# To get categroy with maximum freq
# Index 0 will get the category
cars_data2['MetColor'].mode()[0]

1.0

In [ ]:
# replacing MetColor with mode
cars_data2['MetColor'].fillna(cars_data2['MetColor']\
      .mode()[0], inplace = True)

## Check for missing data after filling values
cars_data2['MetColor'].isnull().sum()

In [ ]:
# Check for missing data after filling values
cars_data2.isnull().sum()


### Imputation using lambda functions

 To fill the NA/ NaN values in both numerical and categorial variables at one stretch

In [ ]:
cars_data3.isnull().sum()

In [ ]:
cars_data3 = cars_data3.apply(
    lambda col: col.fillna(
        cars_data3.groupby('fuel_type')['age'].transform('median')
    ) if col.name == 'age'
    else (
        col.fillna(col.mean()) if pd.api.types.is_numeric_dtype(col)
        else col.fillna(col.mode()[0])
    )
)

print('Data columns with null values:\n', cars_data3.isnull().sum())